/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Etudiant } from './etudiant';
import { Jury } from './jury';

export interface Memoire { 
    id?: number;
    theme?: string;
    urlFile?: string;
    keyworlds?: Array<string>;
    vue?: number;
    telechargement?: number;
    active?: boolean;
    etudiant?: Etudiant;
    jury?: Array<Jury>;
}